; Landmarks indexes (see data/maps/landmarks.asm)
	const_def
	const LANDMARK_SPECIAL
; Johto landmarks
DEF KANSAI_LANDMARK EQU const_value
	const LANDMARK_SILENT_HILLS
	const LANDMARK_KANSAI_ROUTE_1
	const LANDMARK_SAKURA_TOWN
	const LANDMARK_KANSAI_ROUTE_2
	const LANDMARK_EVERGREEN_WOODS
	const LANDMARK_KANSAI_ROUTE_3
	const LANDMARK_DIM_CAVE
	const LANDMARK_BELLFLOWER_CITY
	const LANDMARK_BELL_TOWER
	const LANDMARK_KANSAI_ROUTE_4
	const LANDMARK_ANCIENT_RUINS
	const LANDMARK_LINKING_CAVE
	const LANDMARK_RAINMAKER_WELL
	const LANDMARK_CYPRESS_TOWN
	const LANDMARK_KANSAI_ROUTE_5
	const LANDMARK_CYPRESS_MARSH
	const LANDMARK_BEGONIA_TOWN
	const LANDMARK_KANSAI_ROUTE_6
	const LANDMARK_MARIGOLD_CITY
	const LANDMARK_RADIO_TOWER
	const LANDMARK_KANSAI_ROUTE_7
	const LANDMARK_KANSAI_POWER_PLANT
	const LANDMARK_KANSAI_ROUTE_8
	const LANDMARK_KANSAI_ROUTE_9
	const LANDMARK_MAPLE_CITY
	const LANDMARK_BRASS_TOWER
	const LANDMARK_TIN_TOWER
	const LANDMARK_KANSAI_ROUTE_10
	const LANDMARK_KANSAI_ROUTE_11
	const LANDMARK_AZURE_MIST_CITY
	const LANDMARK_AQUARIUM
	const LANDMARK_LIGHTHOUSE
	const LANDMARK_KANSAI_ROUTE_12
	const LANDMARK_KANSAI_ROUTE_13
	const LANDMARK_WHIRLPOOL_CAVE
	const LANDMARK_KANSAI_ROUTE_14
	const LANDMARK_NATIONAL_PARK
	const LANDMARK_KANSAI_ROUTE_15
	const LANDMARK_CEDAR_FALLS
	const LANDMARK_CEDAR_TOWN
	const LANDMARK_KANSAI_ROUTE_16
	const LANDMARK_REDWOOD_TOWN
	const LANDMARK_KANSAI_ROUTE_17
	const LANDMARK_EBONGROVE_CITY
	const LANDMARK_DRAGON_SHRINE
	const LANDMARK_KANSAI_ROUTE_18
	const LANDMARK_KANSAI_ROUTE_19
	const LANDMARK_KANSAI_ROUTE_20
	const LANDMARK_KANSAI_ROUTE_21
	const LANDMARK_HAUNTED_HOUSE
	const LANDMARK_WINDING_PATH
	const LANDMARK_KANSAI_VICTORY_ROAD
	const LANDMARK_SILVER_CITY
DEF KANTO_LANDMARK EQU const_value
	const LANDMARK_PALLET_TOWN
	const LANDMARK_ROUTE_1
	const LANDMARK_VIRIDIAN_CITY
	const LANDMARK_ROUTE_2
	const LANDMARK_VIRIDIAN_FOREST
	const LANDMARK_PEWTER_CITY
	const LANDMARK_ROUTE_3
	const LANDMARK_MT_MOON
	const LANDMARK_ROUTE_4
	const LANDMARK_CERULEAN_CITY
	const LANDMARK_ROUTE_24
	const LANDMARK_ROUTE_25
	const LANDMARK_ROUTE_5
	const LANDMARK_UNDERGROUND_PATH
	const LANDMARK_ROUTE_6
	const LANDMARK_VERMILION_CITY
	const LANDMARK_DIGLETTS_CAVE
	const LANDMARK_ROUTE_7
	const LANDMARK_ROUTE_8
	const LANDMARK_ROUTE_9
	const LANDMARK_ROCK_TUNNEL
	const LANDMARK_ROUTE_10
	const LANDMARK_POWER_PLANT
	const LANDMARK_LAVENDER_TOWN
	const LANDMARK_POKEMON_TOWER
	const LANDMARK_CELADON_CITY
	const LANDMARK_SAFFRON_CITY
	const LANDMARK_SILPH_CO
	const LANDMARK_ROUTE_11
	const LANDMARK_ROUTE_12
	const LANDMARK_ROUTE_13
	const LANDMARK_ROUTE_14
	const LANDMARK_ROUTE_15
	const LANDMARK_ROUTE_16
	const LANDMARK_ROUTE_17
	const LANDMARK_ROUTE_18
	const LANDMARK_FUCHSIA_CITY
	const LANDMARK_SAFARI_ZONE
	const LANDMARK_ROUTE_19
	const LANDMARK_ROUTE_20
	const LANDMARK_SEAFOAM_ISLANDS
	const LANDMARK_CINNABAR_ISLAND
	const LANDMARK_POKEMON_MANSION
	const LANDMARK_ROUTE_21
	const LANDMARK_ROUTE_22
	const LANDMARK_ROUTE_23
	const LANDMARK_VICTORY_ROAD
	const LANDMARK_INDIGO_PLATEAU
	const LANDMARK_CERULEAN_CAVE
	const LANDMARK_FAST_SHIP
DEF NUM_LANDMARKS EQU const_value

; Regions
	const_def
	const KANSAI_REGION ; 0
	const KANTO_REGION  ; 1
DEF NUM_REGIONS EQU const_value
