	const_def
	const NO_MON             ; $00 *** Placeholder
	const CHIKORITA          ; $01
	const BAYLEEF            ; $02
	const MEGANIUM           ; $03
	const CUBBURN            ; $04
	const FLAMBEAR           ; $05
	const DYNABEAR           ; $06
	const CRUZ               ; $07
	const AQUA               ; $08
	const AQUARIA            ; $09
	const HOOTHOOT           ; $0A
	const NOCTOWL            ; $0B
	const PIDGEY             ; $0C
	const PIDGEOTTO          ; $0D
	const PIDGEOT            ; $0E
	const RATTATA            ; $0F
	const RATICATE           ; $10
	const LEDYBA             ; $11
	const TRIPSTAR           ; $12
	const SPIDETTE           ; $13
	const DUARACH            ; $14
	const CATERPIE           ; $15
	const METAPOD            ; $16
	const BUTTERFREE         ; $17
	const WEEDLE             ; $18
	const KAKUNA             ; $19
	const BEEDRILL           ; $1A
	const SPEAROW            ; $1B
	const FEAROW             ; $1C
	const RINRING            ; $1D
	const BELLBOYANT         ; $1E
	const MEOWSY             ; $1F
	const MEOWTH             ; $20
	const PERSIAN            ; $21
	const KOTORA             ; $22
	const RAITORA            ; $23
	const SANDSHREW          ; $24
	const SANDSLASH          ; $25
	const NIDORAN_F          ; $26
	const NIDORINA           ; $27
	const NIDOQUEEN          ; $28
	const NIDORAN_M          ; $29
	const NIDORINO           ; $2A
	const NIDOKING           ; $2B
	const WOOPER             ; $2C
	const QUAGSIRE           ; $2D
	const MAREEP             ; $2E
	const FLAAFFY            ; $2F
	const AMPHAROS           ; $30
	const BLOSSETTE          ; $31
	const SUNNEE             ; $32
	const PICHU              ; $33
	const PIKACHU            ; $34
	const RAICHU             ; $35
	const JIGGLYPUFF         ; $36
	const WIGGLYTUFF         ; $37
	const CLEFAIRY           ; $38
	const CLEFABLE           ; $39
	const ZUBAT              ; $3A
	const GOLBAT             ; $3B
	const CROBAT             ; $3C
	const PURRLEAF           ; $3D
	const DANDEMEOW          ; $3E
	const COTTONYA           ; $3F
	const TOGEPI             ; $40
	const TOGETIC            ; $41
	const BELLSPROUT         ; $42
	const WEEPINBELL         ; $43
	const VICTREEBEL         ; $44
	const BELLMITT           ; $45
	const ODDISH             ; $46
	const GLOOM              ; $47
	const VILEPLUME          ; $48
	const BELLOSSOM          ; $49
	const PARAS              ; $4A
	const PARASECT           ; $4B
	const VENONAT            ; $4C
	const VENOMOTH           ; $4D
	const EKANS              ; $4E
	const ARBOK              ; $4F
	const SNUBBULL           ; $50
	const GRANBULL           ; $51
	const MARILL             ; $52
	const AZUMARILL          ; $53
	const TAEL               ; $54
	const DIGLETT            ; $55
	const DUGTRIO            ; $56
	const PSYDUCK            ; $57
	const GOLDUCK            ; $58
	const MANKEY             ; $59
	const PRIMEAPE           ; $5A
	const TRIFOX             ; $5B
	const VULPIX             ; $5C
	const NINETALES          ; $5D
	const GROWLIE            ; $5E
	const GROWLITHE          ; $5F
	const ARCANINE           ; $60
	const HOUNDOUR           ; $61
	const HOUNDOOM           ; $62
	const MURKROW            ; $63
	const SMEARGLE           ; $64
	const NATU               ; $65
	const XATU               ; $66
	const UNOWN              ; $67
	const POLIWAG            ; $68
	const POLIWHIRL          ; $69
	const POLIWRATH          ; $6A
	const POLIKING           ; $6B
	const TENTACOOL          ; $6C
	const TENTACRUEL         ; $6D
	const ABRA               ; $6E
	const KADABRA            ; $6F
	const ALAKAZAM           ; $70
	const MACHOP             ; $71
	const MACHOKE            ; $72
	const MACHAMP            ; $73
	const GEODUDE            ; $74
	const GRAVELER           ; $75
	const GOLEM              ; $76
	const ONIX               ; $77
	const STEELIX            ; $78
	const GASTLY             ; $79
	const HAUNTER            ; $7A
	const GENGAR             ; $7B
	const SLOWPOKE           ; $7C
	const SLOWBRO            ; $7D
	const SLOWKING           ; $7E
	const SHELLDER           ; $7F
	const CLOYSTER           ; $80
	const TURBANN            ; $81
	const VOLTORB            ; $82
	const ELECTRODE          ; $83
	const MAGNEMITE          ; $84
	const MAGNETON           ; $85
	const FARFETCHD          ; $86
	const MADAME             ; $87
	const DODUO              ; $88
	const DODRIO             ; $89
	const GRIMER             ; $8A
	const MUK                ; $8B
	const PONYTA             ; $8C
	const RAPIDASH           ; $8D
	const DROWZEE            ; $8E
	const HYPNO              ; $8F
	const EXEGGCUTE          ; $90
	const EXEGGUTOR          ; $91
	const LICKITUNG          ; $92
	const LICKIRAJA          ; $93
	const KOFFING            ; $94
	const WEEZING            ; $95
	const RHYHORN            ; $96
	const RHYDON             ; $97
	const CHANSEY            ; $98
	const HAPPI              ; $99
	const KRABBY             ; $9A
	const KINGLER            ; $9B
	const TANGELA            ; $9C
	const GELANGLA           ; $9D
	const KANGASKHAN         ; $9E
	const HORSEA             ; $9F
	const SEADRA             ; $A0
	const KINGDRA            ; $A1
	const GOLDEEN            ; $A2
	const SEAKING            ; $A3
	const STARYU             ; $A4
	const STARMIE            ; $A5
	const SEEL               ; $A6
	const DEWGONG            ; $A7
	const MR_MIME            ; $A8
	const CUBONE             ; $A9
	const MAROWAK            ; $AA
	const SCYTHER            ; $AB
	const SCIZOR             ; $AC
	const PINSIR             ; $AD
	const PLUX               ; $AE
	const TAUROS             ; $AF
	const MILTANK            ; $B0
	const PHANPY             ; $B1
	const DONPHAN            ; $B2
	const HITMONTYKE         ; $B3
	const HITMONLEE          ; $B4
	const HITMONCHAN         ; $B5
	const HITMONJEAN         ; $B6
	const SKARMORY           ; $B7
	const STANTLER           ; $B8
	const MISDREAVUS         ; $B9
	const TWINZ              ; $BA
	const GIRAFARIG          ; $BB
	const KURSTRAW           ; $BC
	const PANGSHI            ; $BD
	const BOMSEEL            ; $BE
	const KAMEASEL           ; $BF
	const WOLFMAN            ; $C0
	const WARWOLF            ; $C1
	const SWINUB             ; $C2
	const PILOSWINE          ; $C3
	const DELIBIRD           ; $C4
	const JYNX               ; $C5
	const ELECTABUZZ         ; $C6
	const MAGMAR             ; $C7
	const RAYLEEP            ; $C8
	const QWILFISH           ; $C9
	const NUMPUFF            ; $CA
	const SUNMOLA            ; $CB
	const ANCHORAGE          ; $CC
	const GROTESS            ; $CD
	const REMORAID           ; $CE
	const OCTILLERY          ; $CF
	const MAGIKARP           ; $D0
	const GYARADOS           ; $D1
	const LAPRAS             ; $D2
	const DITTO              ; $D3
	const EEVEE              ; $D4
	const VAPOREON           ; $D5
	const JOLTEON            ; $D6
	const FLAREON            ; $D7
	const ESPEON             ; $D8
	const UMBREON            ; $D9
	const LEAFEON            ; $DA
	const OMANYTE            ; $DB
	const OMASTAR            ; $DC
	const KABUTO             ; $DD
	const KABUTOPS           ; $DE
	const AERODACTYL         ; $DF
	const SNORLAX            ; $E0
	const SUDOWOODO          ; $E1
	const PORYGON            ; $E2
	const PORYGON2           ; $E3
	const BULBASAUR          ; $E4
	const IVYSAUR            ; $E5
	const VENUSAUR           ; $E6
	const CHARMANDER         ; $E7
	const CHARMELEON         ; $E8
	const CHARIZARD          ; $E9
	const SQUIRTLE           ; $EA
	const WARTORTLE          ; $EB
	const BLASTOISE          ; $EC
	const DRATINI            ; $ED
	const DRAGONAIR          ; $EE
	const DRAGONITE          ; $EF
	const LARVITAR           ; $F0
	const PUPITAR            ; $F1
	const TYRANITAR          ; $F2
	const ARTICUNO           ; $F3
	const ZAPDOS             ; $F4
	const MOLTRES            ; $F5
	const RAIJIN             ; $F6
	const ENTEN              ; $F7
	const SUIKAMI            ; $F8
	const LUGIA              ; $F9
	const HO_OH              ; $FA
	const MEWTWO             ; $FB
	const MEW                ; $FC
	const SEREBII            ; $FD
DEF NUM_POKEMON EQU const_value - 1
	const MON_GHOST          ; $FE *** For haunted house
DEF NUM_POKEMON_INDEXES EQU const_value - 1

; starters
DEF STARTER1 EQU CUBBURN
DEF STARTER2 EQU CRUZ
DEF STARTER3 EQU CHIKORITA

; ghost Marowak in Pokémon Tower
DEF RESTLESS_SOUL EQU MAROWAK
