; overworld sprites
; SpriteSheetPointerTable indexes (see data/sprites/sprites.asm)
	const_def
	const SPRITE_NONE
	const SPRITE_PLAYER
	const SPRITE_MOM
	const SPRITE_RIVAL
	const SPRITE_ELM
	const SPRITE_BILL
	const SPRITE_KURT
	const SPRITE_GYM_GUIDE
	const SPRITE_FALKNER
	const SPRITE_BUGSY
	const SPRITE_WHITNEY
	const SPRITE_MORTY
	const SPRITE_CHUCK
	const SPRITE_JASMINE
	const SPRITE_PRYCE
	const SPRITE_CLAIR
	const SPRITE_WILL
	const SPRITE_KOGA
	const SPRITE_BRUNO
	const SPRITE_KAREN
	const SPRITE_LANCE
	const SPRITE_REDS_MOM
	const SPRITE_OAK
	const SPRITE_RED
	const SPRITE_BLUE
	const SPRITE_DAISY
	const SPRITE_BROCK
	const SPRITE_MISTY
	const SPRITE_SURGE
	const SPRITE_ERIKA
	const SPRITE_SABRINA
	const SPRITE_JANINE
	const SPRITE_BLAINE
	const SPRITE_LORELEI
	const SPRITE_AGATHA
	const SPRITE_GIOVANNI
	const SPRITE_ROCKET
	const SPRITE_ROCKET_GIRL
	const SPRITE_JESSIE
	const SPRITE_JAMES
	const SPRITE_COOLTRAINER_M
	const SPRITE_COOLTRAINER_F
	const SPRITE_BUG_CATCHER
	const SPRITE_TWIN
	const SPRITE_YOUNGSTER
	const SPRITE_LASS
	const SPRITE_TEACHER
	const SPRITE_BEAUTY
	const SPRITE_SUPER_NERD
	const SPRITE_ROCKER
	const SPRITE_POKEFAN_M
	const SPRITE_POKEFAN_F
	const SPRITE_GRAMPS
	const SPRITE_GRANNY
	const SPRITE_SWIMMER_GUY
	const SPRITE_SWIMMER_GIRL
	const SPRITE_NURSE
	const SPRITE_LINK_RECEPTIONIST
	const SPRITE_CLERK
	const SPRITE_PHARMACIST
	const SPRITE_INN_KEEPER
	const SPRITE_GIRL
	const SPRITE_BALDING_GUY
	const SPRITE_FISHER
	const SPRITE_FISHING_GURU
	const SPRITE_SCIENTIST
	const SPRITE_KIMONO_GIRL
	const SPRITE_ELDER
	const SPRITE_SAGE
	const SPRITE_CHANNELER
	const SPRITE_MEDIUM
	const SPRITE_SAFARI_ZONE_WORKER
	const SPRITE_WARDEN
	const SPRITE_RECEPTIONIST
	const SPRITE_SILPH_GUY
	const SPRITE_SILPH_GIRL
	const SPRITE_SILPH_PRESIDENT
	const SPRITE_GENTLEMAN
	const SPRITE_BLACK_BELT
	const SPRITE_OFFICER
	const SPRITE_OFFICER_JENNY
	const SPRITE_COOK
	const SPRITE_SAILOR
	const SPRITE_CAPTAIN
	const SPRITE_FROWNING_MAN
	const SPRITE_BIKER
	const SPRITE_GAMBLER
	const SPRITE_GAMEBOY_KID
	const SPRITE_MONSTER
	const SPRITE_FAIRY
	const SPRITE_BIRD
	const SPRITE_DRAGON
	const SPRITE_CHANSEY
	const SPRITE_SEEL
	const SPRITE_LAPRAS
	const SPRITE_SURFING_PIKACHU
	const SPRITE_SUDOWOODO

FIRST_STILL_SPRITE EQU const_value
	const SPRITE_POKE_BALL
	const SPRITE_BOOK
	const SPRITE_PAPER
	const SPRITE_CLIPBOARD
	const SPRITE_ROCK
	const SPRITE_BOULDER
	const SPRITE_FOSSIL
	const SPRITE_OLD_AMBER
	const SPRITE_FRUIT_TREE
	const SPRITE_GAMBLER_ASLEEP
	const SPRITE_BENCH_GUY
	const SPRITE_BENCH_LASS
	const SPRITE_BENCH_COOLTRAINER

; Sprites for overworld pokemon Icons
	const SPRITE_ICON_NULL
	const SPRITE_ICON_POLIWAG
	const SPRITE_ICON_JIGGLYPUFF
	const SPRITE_ICON_DIGLETT
	const SPRITE_ICON_PIKACHU
	const SPRITE_ICON_STARYU
	const SPRITE_ICON_FISH
	const SPRITE_ICON_BIRD
	const SPRITE_ICON_MONSTER
	const SPRITE_ICON_CLEFAIRY
	const SPRITE_ICON_ODDISH
	const SPRITE_ICON_BUG
	const SPRITE_ICON_GHOST
	const SPRITE_ICON_LAPRAS
	const SPRITE_ICON_HUMANSHAPE
	const SPRITE_ICON_FOX
	const SPRITE_ICON_EQUINE
	const SPRITE_ICON_SHELL
	const SPRITE_ICON_BLOB
	const SPRITE_ICON_SERPENT
	const SPRITE_ICON_VOLTORB
	const SPRITE_ICON_SQUIRTLE
	const SPRITE_ICON_BULBASAUR
	const SPRITE_ICON_CHARMANDER
	const SPRITE_ICON_CATERPILLAR
	const SPRITE_ICON_UNOWN
	const SPRITE_ICON_GEODUDE
	const SPRITE_ICON_FIGHTER
	const SPRITE_ICON_EGG
	const SPRITE_ICON_JELLYFISH
	const SPRITE_ICON_MOTH
	const SPRITE_ICON_BAT
	const SPRITE_ICON_SNORLAX
	const SPRITE_ICON_HO_OH
	const SPRITE_ICON_LUGIA
	const SPRITE_ICON_GYARADOS
	const SPRITE_ICON_SLOWPOKE
	const SPRITE_ICON_SUDOWOODO
	const SPRITE_ICON_BIGMON
	const SPRITE_ICON_MEWTWO
	const SPRITE_ICON_MEW
NUM_SPRITES EQU const_value - 1

; wVarSprites indexes (see wram.asm)
	const_next $f0
SPRITE_VARS EQU const_value
	const SPRITE_WEIRD_TREE ; f0
	const VAR_SPRITE_2 ; f1
	const VAR_SPRITE_3 ; f2
	const VAR_SPRITE_4 ; f3
	const VAR_SPRITE_5 ; f4
	const VAR_SPRITE_6 ; f5
SPRITE_VARS_END EQU const_value - 1
