	mapconst NEW_BARK_TOWN
	mapconst CHERRYGROVE_CITY
	mapconst VIOLET_CITY
	mapconst AZALEA_TOWN
	mapconst GOLDENROD_CITY
	mapconst ECRUTEAK_CITY
	mapconst OLIVINE_CITY
	mapconst CIANWOOD_CITY
	mapconst MAHOGANY_TOWN
	mapconst BLACKTHORN_CITY
	mapconst LAKE_OF_RAGE
	mapconst MT_SILVER
	mapconst INDIGO_PLATEAU
	mapconst ROUTE_29
	mapconst ROUTE_30
	mapconst ROUTE_31
	mapconst ROUTE_32
	mapconst ROUTE_33
	mapconst ROUTE_34
	mapconst ROUTE_35
	mapconst ROUTE_36
	mapconst ROUTE_37
	mapconst ROUTE_38
	mapconst ROUTE_39
	mapconst ROUTE_40
	mapconst ROUTE_41
	mapconst ROUTE_42
	mapconst ROUTE_43
	mapconst ROUTE_44
	mapconst ROUTE_45
	mapconst ROUTE_46
	mapconst ROUTE_26
	mapconst ROUTE_27
	mapconst ROUTE_28
	mapconst ROUTE_23
	mapconst PLAYERS_HOUSE_1F
	mapconst PLAYERS_HOUSE_2F
	mapconst NEW_BARK_HOUSE_1
	mapconst NEW_BARK_HOUSE_2
	mapconst ELMS_LAB
	mapconst CHERRYGROVE_POKECENTER
	mapconst CHERRYGROVE_MART
	mapconst CHERRYGROVE_HOUSE_1
	mapconst CHERRYGROVE_HOUSE_2
	mapconst GUIDE_GENTS_HOUSE
	mapconst ROUTE_30_BERRY_HOUSE
	mapconst MR_POKEMONS_HOUSE
	mapconst ROUTE_31_GATE
	mapconst DARK_CAVE_1
	mapconst DARK_CAVE_2
	mapconst VIOLET_POKECENTER
	mapconst VIOLET_MART
	mapconst VIOLET_SCHOOL_HOUSE
	mapconst VIOLET_TRADE_HOUSE
	mapconst VIOLET_HOUSE_2
	mapconst VIOLET_GYM
	mapconst SPROUT_TOWER_1F
	mapconst SPROUT_TOWER_2F
	mapconst SPROUT_TOWER_3F
	mapconst RUINS_OF_ALPH_EAST_GATE
	mapconst RUINS_OF_ALPH_NORTH_GATE
	mapconst RUINS_OF_ALPH_LAB
	mapconst RUINS_OF_ALPH_OUTSIDE
	mapconst RUINS_OF_ALPH_1F
	mapconst RUINS_OF_ALPH_B1F
	mapconst RUINS_OF_ALPH_B2F
	mapconst RUINS_OF_ALPH_B3F
	mapconst ROUTE_32_POKECENTER
	mapconst UNION_CAVE_1F
	mapconst UNION_CAVE_B1F
	mapconst UNION_CAVE_B2F
	mapconst AZALEA_POKECENTER
	mapconst AZALEA_MART
	mapconst AZALEA_CHARCOAL_HOUSE
	mapconst KURTS_HOUSE
	mapconst AZALEA_GYM
	mapconst SLOWPOKE_WELL_B1F
	mapconst SLOWPOKE_WELL_B2F
	mapconst ILEX_FOREST_SOUTH_GATE
	mapconst ILEX_FOREST
	mapconst ILEX_FOREST_NORTH_GATE
	mapconst DAY_CARE
	mapconst GOLDENROD_POKECENTER
	mapconst GOLDENROD_MART_1F
	mapconst GOLDENROD_MART_2F
	mapconst GOLDENROD_MART_3F
	mapconst GOLDENROD_MART_4F
	mapconst GOLDENROD_MART_5F
	mapconst GOLDENROD_MART_ROOF
	mapconst GOLDENROD_MART_ELEVATOR
	mapconst GOLDENROD_GYM
	mapconst GAME_CORNER
	mapconst BIKE_SHOP
	mapconst FLOWER_SHOP
	mapconst NAME_RATERS_HOUSE
	mapconst BILLS_HOUSE
	mapconst GOLDENROD_HOUSE
	mapconst GOLDENROD_UNDERGROUND ; entrances and hallway in one
	mapconst TRAIN_STATION ; may not include
	mapconst RADIO_TOWER_1F
	mapconst RADIO_TOWER_2F
	mapconst RADIO_TOWER_3F
	mapconst RADIO_TOWER_4F
	mapconst RADIO_TOWER_5F
	mapconst GOLDENROD_ROCKET_BASE_1
	mapconst GOLDENROD_ROCKET_BASE_2
	mapconst GOLDENROD_ROCKET_BASE_3
	mapconst ROUTE_35_GATE
	mapconst NATIONAL_PARK_SOUTH_GATE
	mapconst NATIONAL_PARK_EAST_GATE
	mapconst NATIONAL_PARK
	mapconst ECRUTEAK_POKECENTER
	mapconst ECRUTEAK_MART
	mapconst ECRUTEAK_HOUSE_1
	mapconst ECRUTEAK_HOUSE_2
	mapconst ECRUTEAK_DANCE_THEATER
	mapconst ECRUTEAK_GYM
	mapconst ECRUTEAK_TOWER_GATE ; all in one
	mapconst BURNED_TOWER_1F
	mapconst BURNED_TOWER_B1F
	mapconst TIN_TOWER_1F
	mapconst TIN_TOWER_2F
	mapconst TIN_TOWER_3F
	mapconst TIN_TOWER_4F
	mapconst TIN_TOWER_5F
	mapconst TIN_TOWER_6F
	mapconst TIN_TOWER_7F
	mapconst TIN_TOWER_8F
	mapconst TIN_TOWER_9F
	mapconst TIN_TOWER_ROOF
	mapconst ROUTE_38_GATE
	mapconst MOO_MOO_FARM
	mapconst MOO_MOO_BARN
	mapconst OLIVINE_POKECENTER
	mapconst OLIVINE_MART
	mapconst OLIVINE_DINER
	mapconst OLIVINE_HOUSE_1
	mapconst OLIVINE_HOUSE_2
	mapconst OLIVINE_HOUSE_3
	mapconst OLIVINE_GYM
	mapconst OLIVINE_DOCK
	mapconst SS_AQUA_1F
	mapconst SS_AQUA_2F
	mapconst SS_AQUA_3F
	mapconst SS_AQUA_B1F
	mapconst SS_AQUA_BOW
	mapconst SS_AQUA_KITCHEN
	mapconst SS_AQUA_CAPTAINS_ROOM
	mapconst SS_AQUA_1F_ROOMS
	mapconst SS_AQUA_2F_ROOMS
	mapconst SS_AQUA_B1F_ROOMS
	mapconst LIGHTHOUSE_1F
	mapconst LIGHTHOUSE_2F
	mapconst LIGHTHOUSE_3F
	mapconst LIGHTHOUSE_4F
	mapconst LIGHTHOUSE_5F
	mapconst LIGHTHOUSE_LIGHT_ROOM
	mapconst WHIRL_ISLANDS_1
	mapconst WHIRL_ISLANDS_2
	mapconst WHIRL_ISLANDS_3
	mapconst WHIRL_ISLANDS_4
	mapconst WHIRL_ISLANDS_5
	mapconst WHIRL_ISLANDS_6
	mapconst WHIRL_ISLANDS_7
	mapconst WHIRL_ISLANDS_8
	mapconst CIANWOOD_POKECENTER
	mapconst CIANWOOD_PHARMACY
	mapconst CIANWOOD_HOUSE_1
	mapconst CIANWOOD_HOUSE_2
	mapconst CIANWOOD_SHUCKIE_HOUSE
	mapconst CIANWOOD_GYM
	mapconst SAFARI_ZONE_GATE
	mapconst SAFARI_ZONE_1
	mapconst SAFARI_ZONE_2
	mapconst SAFARI_ZONE_3
	mapconst ROUTE_42_GATE
	mapconst MT_MORTAR_1
	mapconst MT_MORTAR_2
	mapconst MT_MORTAR_3
	mapconst MT_MORTAR_4
	mapconst MAHOGANY_POKECENTER
	mapconst MAHOGANY_MART
	mapconst MAHOGANY_GYM
	mapconst MAHOGANY_HOUSE
	mapconst ROUTE_43_SOUTH_GATE
	mapconst ROUTE_43_MID_GATE
	mapconst LAKE_OF_RAGE_HOUSE_1
	mapconst LAKE_OF_RAGE_HOUSE_2
	mapconst MAHOGANY_ROCKET_BASE_1
	mapconst MAHOGANY_ROCKET_BASE_2
	mapconst MAHOGANY_ROCKET_BASE_3
	mapconst ICE_PATH_1
	mapconst ICE_PATH_2
	mapconst ICE_PATH_3
	mapconst ICE_PATH_4
	mapconst BLACKTHORN_POKECENTER
	mapconst BLACKTHORN_MART
	mapconst BLACKTHORN_GYM
	mapconst BLACKTHORN_HOUSE_1
	mapconst BLACKTHORN_HOUSE_2
	mapconst BLACKTHORN_HOUSE_3
	mapconst DRAGONS_DEN_ENTRANCE
	mapconst DRAGONS_DEN
	mapconst DRAGON_SHRINE
	mapconst ROUTE_46_GATE
	mapconst ROUTE_27_HOUSE
	mapconst TOHJO_FALLS
	mapconst ROUTE_26_HOUSE_1
	mapconst ROUTE_26_HOUSE_2
	mapconst ROUTE_26_GATE
	mapconst BADGE_CHECK_GATE
	mapconst VICTORY_ROAD_1F
	mapconst VICTORY_ROAD_2F
	mapconst VICTORY_ROAD_3F
	mapconst POKEMON_LEAGUE_LOBBY
	mapconst WILLS_ROOM
	mapconst KOGAS_ROOM
	mapconst BRUNOS_ROOM
	mapconst KARENS_ROOM
	mapconst CHAMPIONS_ROOM
	mapconst HALL_OF_FAME
	mapconst ROUTE_28_POKECENTER
	mapconst SILVER_CAVE_1F
	mapconst SILVER_CAVE_2F
	mapconst SILVER_CAVE_ITEM_ROOMS
	mapconst SILVER_CAVE_SUMMIT
	mapconst TRADE_CENTER
	mapconst COLOSSEUM