- Player Gender
  - Hiro or Kris
- All trainer classes from Gen 1 and 2, for variety
- 251 Pokemon (keep ghost and fossils)
- Look into porting following pokemon from Yellow, but apply to all mons
- Gen 2 party sprites
- R/B shaded sprites with Gen 2 quality
- Shared SGB palettes
- Shininess
- Pokemon Gender
  - Make sure it is shown on the Nickname screen too
- Proper breeding
  - Alternately breeding like RPP3
- Berry Trees on a step counter like RPP3
- Apricorns and special pokeballs
- Bug Catching Contest?
- Johto Safari Zone
- Use HM moves by interacting with cut trees and such like RPP3
- Add headbutt as a field move like RPP3
- Add whirlpool and waterfall as HMs and field moves
  - Look at Cut as a reference for adding Whirlpool as a field move
- Running Shoes and faster bike
- Multiple bugfixes. Look at Shin Pokemon Red, pokered-clean, and red++ repos
- A mixture of Gen 2 moves and custom moves added?
  - Maybe a mix of just Gen 2 and later added?
- Movesets not identical to any generation
- Move Deleter like RPP3
- Move Reminder like RPP3
- Try to mimic some Gen 2 UI things
  - At least try to let you view attack info
- Keep up with enemy pokemon move PP
- Improve trainer AI like RPP3
- Add pockets to the bag
- Remove pointless junk data and messy code, see pokered-clean
- Add roof loading for Johto tilesets
- Port the tileset animation code from Gold
- Possibly redesign rocket hideout to have spinner tiles
- Add ice sliding puzzles like Maize
- Look into porting the surfing pikachu minigame (maybe)
