ChrisFishingTilesFront: INCBIN "gfx/overworld/chris_fish_front.2bpp"
ChrisFishingTilesBack:  INCBIN "gfx/overworld/chris_fish_back.2bpp"
ChrisFishingTilesSide:  INCBIN "gfx/overworld/chris_fish_side.2bpp"
KrisFishingTilesFront:  INCBIN "gfx/overworld/kris_fish_front.2bpp"
KrisFishingTilesBack:   INCBIN "gfx/overworld/kris_fish_back.2bpp"
KrisFishingTilesSide:   INCBIN "gfx/overworld/kris_fish_side.2bpp"
FishingRodTiles:        INCBIN "gfx/overworld/fishing_rod.2bpp"
